In [7]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [8]:
len(revenue)

12

In [9]:
len(expenses)

12

In [10]:
type(revenue)

list

In [11]:
import numpy as np

In [12]:
rev = np.array(revenue)

In [13]:
rev

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [14]:
type(rev)

numpy.ndarray

In [15]:
exp = np.array(expenses)

In [16]:
exp

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [17]:
profit = np.array()

TypeError: Required argument 'object' (pos 1) not found

In [18]:
profit = np.array(rev - exp)

In [19]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [20]:
rev(1) - exp(1)

TypeError: 'numpy.ndarray' object is not callable

In [21]:
rev[1]

7606.46

In [22]:
rev[1]-exp[1]

1911.3900000000003

In [23]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [24]:
profit_after_tax = []
taxrate = .3

In [25]:
for i in range(0,len(profit)):
    profit_after_tax.append((1-taxrate)*profit[i])
    
profit_after_tax

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [26]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [27]:
profit_after_tax

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [28]:
profit_margin = []

In [29]:
profit_margin = np.array()

TypeError: Required argument 'object' (pos 1) not found

In [33]:
profit_margin = np.array(profit_after_tax / rev)

In [31]:
len(profit_after_tax)

12

In [32]:
len(rev)

12

In [34]:
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [35]:
rev

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [36]:
exp

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [37]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [38]:
profit_after_tax

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [39]:
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [40]:
np.mean(profit_margin)

0.151585493533863

In [41]:
np.mean(profit_after_tax)

1750.6813333333332

In [42]:
#create a list of years where profit_after_tax was greater than the mean

In [43]:
rev = rev/1000

In [44]:
rev

array([14.57449,  7.60646,  8.61141,  9.17541,  8.05865,  8.10544,
       11.49628,  9.76609, 10.30532, 14.37996, 10.71397, 15.4335 ])

In [45]:
rev = rev*1000

In [46]:
rev

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [47]:
exp

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [48]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [49]:
profit_after_tax

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [51]:
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [52]:
profit_after_tax[0]>np.mean(profit_after_tax)

True

In [53]:
profit_above_mean = []

for i in range(0,len(profit_after_tax)):
    profit_above_mean.append(profit_after_tax[i]>np.mean(profit_after_tax))

profit_above_mean

[True, False, False, False, False, True, True, True, True, False, False, True]

In [54]:
profit_below_mean = []

for i in range(0,len(profit_after_tax)):
    profit_below_mean.append(profit_after_tax[i]<np.mean(profit_after_tax))
    
profit_below_mean

[False, True, True, True, True, False, False, False, False, True, True, False]

In [55]:
max_profit_year = np.max(profit_after_tax)

In [56]:
max_profit_year

8140.678

In [57]:
min_profit_year = np.min(profit_after_tax)
min_profit_year

-2595.4530000000004

In [58]:
#summary of answers for the homework assigment

In [59]:
#profit for each month

print(profit)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]


In [60]:
#profit after tax rate each month (tax rate = 30%)

print(taxrate)
print(profit_after_tax)

0.3
[1765.869, 1337.9730000000002, -2595.4530000000004, -2040.0169999999996, -419.944, 5085.668, 5747.385, 2761.479, 2329.8729999999996, -1567.055000000001, 461.71999999999895, 8140.678]


In [61]:
#profit margin for each month - equals to profit after tax divided by revenue

print(profit_margin)

[ 0.12116163  0.17589956 -0.30139698 -0.22233524 -0.05211096  0.62743886
  0.49993433  0.28276199  0.22608449 -0.10897492  0.04309514  0.52746804]


In [68]:
#good months - where the profit after tax was greater than the mean for the year
#bad months - where the profit after tax was less than the mean for the year

#the new array applies boolean logic to each element.
#True is a good month (profit greater than mean) 
#False is a mad month (profit not greater than mean

print(profit_above_mean)

#test case

print("Mean profit after tax:", np.mean(profit_after_tax))

print("Profit for year 1 is", profit_after_tax[0], "so good year is",profit_above_mean[0])
print("Profit for year 2 is", profit_after_tax[1], "so good year is",profit_above_mean[1])

[True, False, False, False, False, True, True, True, True, False, False, True]
Mean profit after tax: 1750.6813333333332
Profit for year 1 is 1765.869 so good year is True
Profit for year 2 is 1337.9730000000002 so good year is False
